environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

os:
  - Windows Server 2012 R2

build: off

version: "{build}"
